# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bulletinboard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bulletinboard
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'SwiftyJSON'
  pod 'JSQMessagesViewController'

  target 'bulletinboardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bulletinboardUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
